package com.neuedu.dao;

import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.sql.Timestamp;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    //发货

//    int updateByPrimaryKey2(Order record);
    List<Order> findOrderByUserid(Integer userId);

    Order findOrderByOrderNo(Long orderNo);


    Order findOrderByOrderNoAndUserId(@Param("userId") Integer userId,
                                      @Param("orderNo") Long orderNo);

    int findOrderStatusByOrderNo(Long orderNo);

    String selectSendTimeByOrderNo(Long orderNo);


    /**
     * 按照创建时间查询订单
     * */
    List<Order> findOrderByCreateTime(@Param("orderStatus") Integer orderStatus,
                                      @Param("time") String time);
}